[project]
name = "intellioptics"
version = "0.24.2"
description = "IntelliOptics SDK & CLI"
readme = "README.md"
requires-python = ">=3.9,<4.0"
license = { text = "MIT" }
dependencies = [
  "pydantic>=1.10,<3",
  "requests>=2.28.2,<3",
  "python-dateutil>=2.9,<3",
  "pillow>=9",
  "typer>=0.12.3,<0.13",
  "frozendict>=2.3.2,<3",
  "urllib3>=1.26.9,<2",
  "certifi>=2023.7.22",
]
[project.scripts]
intellioptics = "intellioptics.cli:app"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
