[project]
name = "intellioptics"
version = "0.24.2"
description = "IntelliOptics SDK & CLI"
readme = "README.md"
requires-python = ">=3.9,<4.0"
license = { text = "MIT" }
dependencies = [
  "pydantic>=2,<3",
  "requests>=2.28,<3",
  "typer>=0.12,<0.13",
  "python-dateutil>=2.9,<3",
  "pillow>=9",
]
[project.scripts]
intellioptics = "intellioptics.cli:app"
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
