name: ci
on:
  push: { branches: ["main"] }
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install -U pip hatch
      - run: python -m pip install .[test]
      - run: pytest -q
      - run: hatch build