name: Deploy API to Azure App Service

on:
  push:
    branches: [ main ]
    paths:
      - "api/**"
      - ".github/workflows/api-deploy.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create a zip with the *contents* of api/ at the root of the zip
      - name: Package API
        run: |
          cd api
          zip -r ../api-package.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: intellioptics-api-37558
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: api-package.zip
