name: SDK CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
<<<<<<< HEAD
          pip install requests pytest

      - name: Run tests
        run: |
          export PYTHONPATH=.
=======
          pip install requests
          pip install pytest

      - name: Run tests
        run: |
>>>>>>> 5f1bbe5 (Initial commit of IntelliOptics SDK)
          pytest tests
